apiVersion: v1 
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    app: php-apache
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: <Target Port>
  clusterIP: none

